### ISSUE TITLE
Joint name

### ISSUE THREAD

**Issue by triccyx** [robotology/gazebo-fmi#11]
In gazebo-fmi Actuator plugin line 33

> The total list of joints contained in the model is scanned and the first joint that ends with this name string is found. This is done to easily support nested models.

Is not true as the code is

 `joint = _parent->GetJoint(jointName);`

So for example
`<joint>L_AK_R</joint> 
`
doesn't work while 

`<joint>robot-fixed::robot-yarp::AB-01::L_AK_R</joint> `

works.

We need to substitute with  a substring search on all the Joints

**Comment by traversaro** [comment]
You are right, I probably wrote the documentation wanting to do that modification but I did not did it. You can get the necessary code in https://github.com/robotology/gazebo-yarp-plugins/blob/master/plugins/controlboard/src/ControlBoardDriver.cpp#L731 (you can just copy&paste the hasEnding function).

**Comment by triccyx** [comment]
I have had already written the small function.

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/gazebo-fmi/pull/12 .
