### ISSUE TITLE
Add FMU generation from OpenModelica to documentation

### ISSUE THREAD

**Issue by triccyx** [robotology/gazebo-fmi#14]
It could be useful to add in modelica-actuator.md the way to generate the FMU from .mo files (In OpenModelica).
In particular, I find out that dynamic library generation is working while static generation for unknown reasons is not.

**Comment by traversaro** [comment]
I agree, feel free to modify the docs!

**Comment by traversaro** [comment]
![complianttransmission](https://user-images.githubusercontent.com/1857049/43839216-d980bbc4-9b1d-11e8-81b4-eedfd46f4760.png)
![identitytransmission](https://user-images.githubusercontent.com/1857049/43839217-d9a7acac-9b1d-11e8-8dba-e5548d3c874f.png)
![nulltransmission](https://user-images.githubusercontent.com/1857049/43839218-d9c9960a-9b1d-11e8-8b2c-fbd712a0ff4a.png)
![softtransmission](https://user-images.githubusercontent.com/1857049/43839219-d9eb899a-9b1d-11e8-8475-9bd36f585d7c.png)
![stifftransmission](https://user-images.githubusercontent.com/1857049/43839220-da165d3c-9b1d-11e8-81b2-0ff04d149980.png)
