### ISSUE TITLE
Get and build FMILibrary using CMake's FetchContent 

### ISSUE THREAD

**Issue by traversaro** [robotology/gazebo-fmi#2]
The main dependency of this plugin [FMILibrary](https://jmodelica.org/fmil/FMILibrary-2.0.3-htmldoc/index.html) is not packaged on most package managers. For simplify the installation when the plugin is not built as part of a superbuild, it may be worth to investigate the possibility of optionally including the library using the new CMake module [FetchContent](https://cmake.org/cmake/help/v3.11/module/FetchContent.html). 
This module could be used also for getting exactly the google-test version required by the Gazebo testing infrastructure.

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/gazebo-fmi/pull/23 , thanks @prashanthr05 .

**Comment by prashanthr05** [comment]
Closing issue. See PR #23
