### ISSUE TITLE
RPATH error

### ISSUE THREAD

**Issue by triccyx** [robotology/gazebo-fmi#47]
While 
`sudo make install `
an error appear. Look at the log.log included.
But if I try with
`objdump -x  /usr/local/lib/libGazeboFMIPrivateUtils.so | grep RPATH
`
the result is:
`  RPATH                /home/ltricerri/FMILibrary/install/lib`

**Comment by triccyx** [comment]
[log.log](https://github.com/robotology/gazebo-fmi/files/2749854/log.log)

**Comment by traversaro** [comment]
The actual error is quite interesting:
~~~
CMake Error at libraries/private-utils/cmake_install.cmake:50 (file):
  file RPATH_CHANGE could not write new RPATH:

    

  to the file:

    /usr/local/lib/libGazeboFMIPrivateUtils.so

  The current RPATH is:

    /home/ltricerri/FMILibrary/install/lib

  which does not contain:

    /home/ltricerri/FMILibrary/install/lib:
~~~
Do you have the same error also on a clean build?

**Comment by traversaro** [comment]
FMILibrary is compiled internally or is available externally?

**Comment by triccyx** [comment]
FMILibrary is compiled. It is not a prebuilt binary.
If
```
rm build 
mkdir build
cmake ..
...
```

all works! I think it was some sort of problems due to old builds. We can close issue if you agree.

**Comment by traversaro** [comment]
> FMILibrary is compiled. It is not a prebuilt binary.

Compiled internally by using `FetchContent`, or compiled externally in a superbuild?

**Comment by traversaro** [comment]
>  I think it was some sort of problems due to old builds. We can close issue if you agree.

Agreed, but it is good to have a reference to it if someone has some similar problem.
