### ISSUE TITLE
Enabled flag 

### ISSUE THREAD

**Issue by triccyx** [robotology/gazebo-fmi#50]
It would be useful the possibilitie to disable an FMU from the *.sdf file via global plugin flag <enabled> default true.

```

 <plugin name="HED_R_fmi_actuator_plugin" filename="libFMIActuatorPlugin.so">
        <enabled>true</enabled>
        <verbose>false</verbose>
```
In this way we can avoid to comment the plugin lines in sdf if the FMU is not necessary

**Comment by traversaro** [comment]
To be honest I am not a big fan of it, but I do not think it can create big maintainability problems if introduced, so feel free to open a PR, thanks!

**Comment by triccyx** [comment]
Resolved
