### ISSUE TITLE
Update documentation on how to run the tests

### ISSUE THREAD

**Issue by triccyx** [robotology/gazebo-fmi#9]
Trying:
` ctest [-VV]`
result
<<No tests were found!!!>>
I have tried around:
<<gazebo-fmi/build/>>

**Comment by traversaro** [comment]
The documentation is incomplete, my fault. You should make sure that you have OpenModelica installed, and you should set the `BUILD_TESTING` variable to `ON`.

**Comment by triccyx** [comment]
An error still occurs in file LastTest.log:


Output:
----------------------------------------------------------
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from PhysicsEngines/FMIActuatorPluginTest
[ RUN      ] PhysicsEngines/FMIActuatorPluginTest.PluginTest/0
[Dbg] [FMIActuatorPluginTest.cc:88] Adding /home/ltricerri/gazebo-fmi/build/lib to the GAZEBO_PLUGIN_PATH
[Dbg] [FMIActuatorPluginTest.cc:90] Adding /home/ltricerri/gazebo-fmi/build/plugins/actuator/test to the GAZEBO_RESOURCE_PATH
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 10.255.111.107
[Err] [Plugin.hh:180] Failed to load plugin /usr/local/lib/libFMIActuatorPlugin.so: libfmilib_shared.so: cannot open shared object file: No such file or directory


My library libfmilib_shared.so is in:
/usr/lib/x86_64-linux-gnu/omc/libfmilib_shared.so
so in order to make the test starts:

```
sudo ln -s /usr/lib/x86_64-linux-gnu/omc/libfmilib_shared.so /usr/lib/x86_64-linux-gnu
sudo ldconfig


```

**Comment by triccyx** [comment]
Now the test works but fails.

[LastTest.log](https://github.com/robotology-playground/gazebo-fmi/files/2198143/LastTest.log)

**Comment by traversaro** [comment]
Are you using the `improveDocsAndTests` of the PR https://github.com/robotology-playground/gazebo-fmi/pull/6 ? Before the PR, the testing infrastructure was not finalized.

**Comment by traversaro** [comment]
~~~
[Err] [Plugin.hh:180] Failed to load plugin /usr/local/lib/libFMIActuatorPlugin.so: libfmilib_shared.so: cannot open shared object file: No such file or directory

My library libfmilib_shared.so is in:
/usr/lib/x86_64-linux-gnu/omc/libfmilib_shared.so
~~~
This is strange, if you have downloaded and compiled a local copy of the FMILibrary, the plugin should link your local copy, not the one provided by OpenModelica? What's the output of `cat CMakeCache.txt | grep FMI` in the build directory of `gazebo-fmi` ?

**Comment by traversaro** [comment]
@triccyx Did you solve this issue?

**Comment by triccyx** [comment]
No the test still fails. At the moment is not a problem about loading libfmilib_shared.so
I include the log.

[LastTest.log](https://github.com/robotology/gazebo-fmi/files/2210790/LastTest.log)

**Comment by traversaro** [comment]
That's interesting, it seems that the results is slightly different, but different enough to violate the tolerance. Which Gazebo version are you using? I run the tests using: 
* Ubuntu 18.04 
* Gazebo  9.2.0
* OpenModelica 1.12.0~4-g83bba97

**Comment by triccyx** [comment]
Ubuntu 16.04
Gazebo 8.6.0
OpenModelica 1.12.0~4-g83bba97 --> now the nightly build I can't check the version because I have no more the menu bar. However some result with OpenModelica 1.12.0~4-g6d56dda

**Comment by traversaro** [comment]
> but I can't check the exact version because I have no more the menu bar. 

You can get the version from commandline  using `omc --version`.
